twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        ## Ajout d'un theme bootstrap aux formulaires
        form_themes: [ 'bootstrap_5_layout.html.twig' ]
        strict_variables: true

